import Login from "@/components/Login";
import React from "react";

export const metadata = {
  title: "SignIn",
  description: "Generated by create next app",
};

const page = () => {
  return <Login />;
};

export default page;
