import React from "react";
export const metadata = {
  title: "SignUp",
  description: "Generated by create next app",
};

import Register from "@/components/Register";
const page = () => {
  return <Register />;
};

export default page;
